#!/bin/bash

# set up castle
export CASTLE_NAME=`echo $HOMESICK_CASTLE | sed "s/[^\/]*\///"`
yes 'n' | homesick clone $HOMESICK_CASTLE
yes 'n' | homesick link $CASTLE_NAME
yes | homesick rc $CASTLE_NAME

exit 0
