#!/usr/bin/env bash
# vim: filetype=sh

DOCKER_NETWORK=scraw
CONTAINER_NAME=scraw
SCRAW=nkcraddock/scraw:latest
if [ ! -z $1 ]; then
  SCRAW=$1
fi

DIR="${HOME}/.scraw"
DIRSSH="$DIR/.ssh"
DIRSOCK="$DIR/.sock"


[ ! -d "$DIRSSH" ] && mkdir -p $DIRSSH
[ ! -d "$DIRSOCK" ] && mkdir -p $DIRSOCK

if [ ! -e $DIRSSH/id_rsa ]; then                                                                                                                          
  echo "Generating ssh keys in $DIRSSH"
  ssh-keygen -t rsa -C "SCRAW" -f $DIRSSH/id_rsa -P ""
fi

echo "running $SCRAW"

if $(docker network ls | grep $DOCKER_NETWORK &> /dev/null); then
  echo "create network"
fi
docker run --name $CONTAINER_NAME -v $DIRSSH:/root/.ssh -v $(pwd):/root/dev --rm -it --hostname "SCRAW" --net=$DOCKER_NETWORK $SCRAW 
docker network connect $DOCKER_NETWORK $CONTAINER_NAME
