#!/usr/bin/env bash
# vim: filetype=sh

SCRAW=nkcraddock/scraw:latest
if [ ! -z $1 ]; then
  SCRAW=$1
fi

DIR="${HOME}/.scraw"
DIRSSH="$DIR/.ssh"
DIRSOCK="$DIR/.sock"


[ ! -d "$DIRSSH" ] && mkdir -p $DIRSSH
[ ! -d "$DIRSOCK" ] && mkdir -p $DIRSOCK

if [ ! -e $DIRSSH/id_rsa ]; then                                                                                                                          
  echo "Generating ssh keys in $DIRSSH"
  ssh-keygen -t rsa -C "SCRAW" -f $DIRSSH/id_rsa -P ""
fi

echo "running $SCRAW"

docker run -v $DIRSSH:/root/.ssh -v $(pwd):/root/dev --rm -it --hostname "SCRAWWWWWWWW" $SCRAW 
