#!/usr/bin/env bash
# vim: filetype=sh
#

# Download homeshick
git clone --depth=1 https://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick

# Use homeshick to download and link default dotfiles
source $HOME/.homesick/repos/homeshick/homeshick.sh
#yes | homeshick clone -b nkcraddock/scraw-dotfiles
#yes | homeshick link scraw-dotfiles

# Set homeshick to autoload in bash local
echo 'source $HOME/.homesick/repos/homeshick/homeshick.sh' >> $HOME/.bash_local

# Set up homeshick aliases
echo 'alias homesick="homeshick"' >> $HOME/.bash_local
echo 'alias hs="homeshick"' >> $HOME/.bash_local

